name: comp30830
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - anyio=3.7
  - appnope=0.1
  - argon2-cffi=23.1
  - arrow=1.3
  - asttokens=2.4
  - async-lru=2.0
  - attrs=23.2
  - babel=2.14
  - beautifulsoup4=4.12
  - bleach=6.1
  - brotli=1.1
  - bzip2=1.0
  - ca-certificates
  - certifi
  - cffi=1.16
  - charset-normalizer=3.3
  - decorator=5.1
  - defusedxml=0.7
  - entrypoints=0.4
  - executing=2.0
  - h11=0.14
  - h2=4.1
  - httpcore=1.0
  - httpx=0.27
  - hyperframe=6.0
  - idna=3.6
  - importlib-metadata=7.0
  - importlib_resources=6.3
  - ipykernel=6.29
  - ipython=8.22
  - jedi=0.19
  - jinja2=3.1
  - json5=0.9
  - jsonpointer=2.0
  - jsonschema=4.21
  - jupyter_client=7.4
  - jupyter_core=5.5
  - jupyterlab=4.1
  - matplotlib-inline=0.1
  - nbclient=0.10
  - nbconvert-core=7.16
  - nbformat=5.10
  - nest-asyncio=1.6
  - notebook=7.1
  - openssl
  - pandocfilters=1.5
  - parso=0.8
  - pexpect=4.9
  - pickleshare=0.7
  - pip
  - platformdirs=4.2
  - prometheus_client=0.20
  - prompt-toolkit=3.0
  - psutil=5.9
  - pycparser=2.21
  - pygments=2.17
  - pysocks=1.7
  - python-dateutil=2.8
  - pytz=2024.1
  - pyyaml=6.0
  - pyzmq=24.0
  - readline=8.2
  - requests=2.31
  - setuptools
  - six=1.16
  - sniffio=1.3
  - soupsieve=2.5
  - sqlite=3.41
  - terminado=0.18
  - tinycss2=1.2
  - tk=8.6
  - tornado=6.3
  - traitlets=5.14
  - typing_extensions=4.10
  - urllib3
  - wheel
  - xz=5.4
  - yaml=0.2
  - zeromq=4.3
  - zlib=1.2
  - pip:
      - absl-py==2.1.0
      - adapt==0.4.4
      - apscheduler==3.10.4
      - astunparse==1.6.3
      - blinker==1.7
      - cattrs==23.2
      - click==8.1
      - cloudpickle==3.0
      - cmdstanpy==1.2
      - contourpy==1.2
      - cryptography==42.0
      - cvxopt==1.3
      - cycler==0.12
      - cython==3.0
      - dm-tree==0.1
      - flask==3.0
      - flask-login==0.6
      - flask-sqlalchemy==3.1
      - flatbuffers==23.5
      - fonttools==4.49
      - gast==0.5
      - google-pasta==0.2
      - grpcio==1.62
      - h5py==3.10
      - holidays==0.44
      - importlib-resources==6.1
      - itsdangerous==2.1
      - joblib==1.3
      - keras==3.0
      - keras-tuner==1.4
      - kiwisolver==1.4
      - kt-legacy==1.0
      - libclang==16.0
      - markdown==3.5
      - markdown-it-py==3.0
      - markupsafe==2.1
      - matplotlib==3.8
      - mdurl==0.1
      - ml-dtypes==0.3
      - namex==0.0
      - numpy==1.26
      - openmeteo-requests==1.2
      - openmeteo-sdk==1.10
      - opt-einsum==3.3
      - packaging==21.3
      - pandas==2.2
      - patsy==0.5
      - pillow==10.2
      - plotly==5.19
      - pmdarima==2.0
      - prophet==1.1
      - protobuf==4.25
      - pyaml==23.12
      - pymysql==1.1
      - pyparsing==3.1
      - python-dotenv==1.0
      - requests-cache==1.2
      - retry-requests==2.0
      - rich==13.7
      - scikeras==0.4
      - scikit-learn==1.4
      - scikit-optimize==0.10
      - scipy==1.12
      - seaborn==0.13
      - sklearn-pandas==2.2
      - sqlalchemy==2.0
      - stanio==0.3
      - statsmodels==0.14
      - tabulate==0.9
      - tenacity==8.2
      - tensorboard==2.16
      - tensorboard-data-server==0.7
      - tensorflow==2.16
      - termcolor==2.4
      - threadpoolctl==3.3
      - tqdm==4.66
      - tzdata==2024.1
      - tzlocal==5.2
      - url-normalize==1.4
      - urllib3==2.2
      - werkzeug==3.0
      - wrapt==1.16
      - xgboost==2.0